services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certificates.certFile=/certs/cert.pem"
      - "--entrypoints.websecure.http.tls.certificates.keyFile=/certs/key.pem"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs"
    restart: always

  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.signage.rule=Host(`10.0.201.55`)"
      - "traefik.http.routers.signage.entrypoints=websecure"
    restart: always
